/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ffmpeg_jni_VideoDash */

#ifndef _Included_ffmpeg_jni_VideoDash
#define _Included_ffmpeg_jni_VideoDash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ffmpeg_jni_VideoDash
 * Method:    getVideoDash
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ffmpeg_1jni_VideoDash_getVideoDash  (JNIEnv *, jobject, jstring);
static void logging(const char *fmt, ...);
int getVideoDash( const char* inputFileName);


#ifdef __cplusplus
}
#endif
#endif
